on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run WDIO tests
    steps:
      - name: Start selenoid
        uses: Xotabu4/selenoid-github-action@v2
        id: start-selenoid
        continue-on-error: false
        with:
          selenoid-start-arguments: |
            --browsers-json ./config/devices.json
            

      #- uses: actions/checkout@v1
      #- run: mvn package
