name: Appium CI

on: [push]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # need checkout before using compose-action
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.1.0
        with:
          compose-file: "./appium-grid-compose.yml"
      # Build Android App and Run Tests
      - name: Run Test
        run: mvn package
        continue-on-error: true