name: Appium CI

on: [push]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # need checkout before using compose-action
      - uses: actions/checkout@v2

      - name: Build docker
        run: docker-compose -f appium-grid-compose.yml up -d

      - name: Sleep
        uses: jakejarvis/wait-action@master
        with:
          time: '60s'

      # Build Android App and Run Tests
      - name: Run Test
        run: mvn package
        continue-on-error: true